# This dataset config is same as the "data" in 
# "config/centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py" 
# in mmdetection3d, except that we not use "CBGSDataset" and not contain the 
# "samples_per_gpu" and "workers_per_gpu" in this config.


TRAIN:
    type: CBGSDataset 
    dataset:
        type: NuScenesDataset
        data_root: data/nuscenes/
        ann_file: data/nuscenes/nuscenes_infos_train.pkl
        classes: [
            car, truck, construction_vehicle, bus, trailer, barrier,
            motorcycle, bicycle, pedestrian, traffic_cone
        ]
        modality: {
            use_lidar: True,
            use_camera: False,
            use_radar: False,
            use_map: False,
            use_external: False
        }
        test_mode: False
        use_valid_flag: True
        # we use box_type_3d='LiDAR' in kitti and nuscenes dataset
        # and box_type_3d='Depth' in sunrgbd and scannet dataset.
        box_type_3d: LiDAR
        tasks: [detection, lidarseg]
        pipeline: [
            {
                type: LoadPointsFromFile,
                coord_type: LIDAR,
                load_dim: 5,
                use_dim: 5,
                file_client_args: {backend: disk}
            },
            {
                type: LoadPointsFromMultiSweeps,
                sweeps_num: 9,
                use_dim: [0, 1, 2, 3, 4],
                file_client_args: {backend: disk},
                pad_empty_sweeps: True,
                remove_close: True
            },
            {
                type: LoadAnnotations3D, 
                with_bbox_3d: True, 
                with_label_3d: True,
                with_seg_3d: True,
                seg_3d_dtype: uint8
            },
            {type: NuScenesPointSegClassMapping},
            {
                type: NuScenesSematicObjectSample,
                tulpe_info_path: data/nuscenes/nuscenes_dbcache_trainval.pkl, 
                data_root: data/nuscenes/, 
                sample_cls: [
                    car, truck, construction_vehicle, bus, trailer, barrier,
                    motorcycle, bicycle, pedestrian, traffic_cone
                ],
                max_sample: [4, 5, 12, 7, 10, 4, 10, 10, 4, 4], 
                min_sample: [2, 3, 7, 4, 6, 2, 6, 6, 2, 2], 
                min_points: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 
                mix_range: [-54, -54, 54, 54], 
                granularity: 0.5, 
                depth_allowance: 1, 
                transforms: None,
                collision: False, 
                mix_on_points: False, 
                refresh_cache: False,  # True, 
                info_path: data/nuscenes/nuscenes_dbinfos_trainval.pkl,
                points_loader: {
                    type: LoadPointsFromFile, 
                    coord_type: LIDAR, 
                    load_dim: 5, 
                    use_dim: [0, 1, 2, 3, 4],
                    file_client_args: {backend: disk}
                }
            },
            {
                type: GlobalRotScaleTrans,
                rot_range: [-0.3925, 0.3925],
                scale_ratio_range: [0.95, 1.05],
                translation_std: [0, 0, 0]
            },
            {
                type: RandomFlip3D, 
                sync_2d: False,
                flip_ratio_bev_horizontal: 0.5,
                flip_ratio_bev_vertical: 0.5
            },
            {type: PointsRangeFilter, point_cloud_range: [-54, -54, -5.0, 54, 54, 3.0]},
            {type: ObjectRangeFilter, point_cloud_range: [-54, -54, -5.0, 54, 54, 3.0]},
            {
                type: ObjectNameFilter, 
                classes: [
                    car, truck, construction_vehicle, bus, trailer, barrier,
                    motorcycle, bicycle, pedestrian, traffic_cone
                ]
            },
            {type: PointShuffle},
            {
                type: DefaultFormatBundle3D, 
                class_names: [
                    car, truck, construction_vehicle, bus, trailer, barrier,
                    motorcycle, bicycle, pedestrian, traffic_cone
                ]
            },
            {type: Collect3D, keys: [points, gt_bboxes_3d, gt_labels_3d]}
        ]

VAL:
    type: NuScenesDataset
    data_root: data/nuscenes/
    ann_file: data/nuscenes/nuscenes_infos_val.pkl
    classes: [
        car, truck, construction_vehicle, bus, trailer, barrier,
        motorcycle, bicycle, pedestrian, traffic_cone
    ]
    modality: {
        use_lidar: True,
        use_camera: False,
        use_radar: False,
        use_map: False,
        use_external: False
    }
    test_mode: True
    box_type_3d: LiDAR
    pipeline: [
        {
            type: LoadPointsFromFile,
            coord_type: LIDAR,
            load_dim: 5,
            use_dim: 5,
            file_client_args: {backend: disk}
        },
        {
            type: LoadPointsFromMultiSweeps,
            sweeps_num: 9,
            use_dim: [0, 1, 2, 3, 4],
            file_client_args: {backend: disk},
            pad_empty_sweeps: True,
            remove_close: True
        },
        {
            type: MultiScaleFlipAug3D,
            img_scale: [1333, 800],
            pts_scale_ratio: 1,
            flip: False,
            transforms: [
                {
                    type: GlobalRotScaleTrans,
                    rot_range: [0, 0],
                    scale_ratio_range: [1., 1.],
                    translation_std: [0, 0, 0]
                },
                {type: RandomFlip3D},
                {type: PointsRangeFilter, point_cloud_range: [-54, -54, -5.0, 54, 54, 3.0]},
                {
                    type: DefaultFormatBundle3D,
                    class_names: [
                        car, truck, construction_vehicle, bus, trailer, barrier,
                        motorcycle, bicycle, pedestrian, traffic_cone
                    ],
                    with_label: False
                },
                {type: Collect3D, keys: [points]}
            ]
        }
    ]


TEST:
    type: NuScenesDataset
    data_root: data/nuscenes/
    ann_file: data/nuscenes/nuscenes_infos_val.pkl
    classes: [
        car, truck, construction_vehicle, bus, trailer, barrier,
        motorcycle, bicycle, pedestrian, traffic_cone
    ]
    modality: {
        use_lidar: True,
        use_camera: False,
        use_radar: False,
        use_map: False,
        use_external: False
    }
    test_mode: True
    box_type_3d: LiDAR
    pipeline: [
        {
            type: LoadPointsFromFile,
            coord_type: LIDAR,
            load_dim: 5,
            use_dim: 5,
            file_client_args: {backend: disk}
        },
        {
            type: LoadPointsFromMultiSweeps,
            sweeps_num: 9,
            use_dim: [0, 1, 2, 3, 4],
            file_client_args: {backend: disk},
            pad_empty_sweeps: True,
            remove_close: True
        },
        {
            type: MultiScaleFlipAug3D,
            img_scale: [1333, 800],
            pts_scale_ratio: 1,
            flip: False,
            transforms: [
                {
                    type: GlobalRotScaleTrans,
                    rot_range: [0, 0],
                    scale_ratio_range: [1., 1.],
                    translation_std: [0, 0, 0]
                },
                {type: RandomFlip3D},
                {type: PointsRangeFilter, point_cloud_range: [-54, -54, -5.0, 54, 54, 3.0]},
                {
                    type: DefaultFormatBundle3D,
                    class_names: [
                        car, truck, construction_vehicle, bus, trailer, barrier,
                        motorcycle, bicycle, pedestrian, traffic_cone
                    ],
                    with_label: False
                },
                {type: Collect3D, keys: [points]}
            ]
        }
    ]
